# This file was adapted from work by Keith James (keithj) and Jaime Tovar Corona
# (jmtc). The original source can be found as part of the wtsi-npg/data_handling
# and wtsi-npg/qc projects here:
#
#   https://github.com/wtsi-npg/data_handling
#   https://github.com/wtsi-npg/npg_qc

sudo: required

language: perl

perl:
  - "5.22-shrplib"

env:
  global:
    - SH=bash
    - DNAP_UTILITIES_VERSION="0.5.1"
    - BWA_VERSION="0.5.10-mt_fixes.2"
    - BWA0_6_VERSION="v0.7.13"
    - BLAT_VERSION="35"
    - BOWTIE_VERSION="v1.0.1-dkj-fopen_with_MM"
    - BOWTIE2_VERSION="v2.2.7"
    - STADEN_IO_LIB_VERSION="1.14.6"
    - BIOBAMBAM_VERSION="2.0.50-release-20160705161609"
    - HTSLIB_VERSION="1.6"
    - SAMTOOLS_VERSION="1.6"
    - PICARD_VERSION="1.72"
    - STAR_VERSION="2.5.2b"
    - TOOLS_INSTALLED=1
#    - TEST_AUTHOR=1 # disabled to avoid perl critic complaints
    - MACHTYPE="`uname -m`"
    - CLASSPATH="/tmp/picard-tools-${PICARD_VERSION}"
    - PATH="$PATH:/tmp/bin:/tmp/biobambam2/bin:$HOME/bin/$MACHTYPE"
    - LD_LIBRARY_PATH="/usr/local/lib:$HOME/lib/$MACHTYPE"


before_install:
 - ./.travis/before_install.sh
install:
 - ./.travis/install.sh
script:
 - ./.travis/script.sh
