#!/usr/bin/env perl
#########
# Author:        gq1
# Maintainer:    $Author$
# Created:       2011-03-10
# Last Modified: $Date$
# Id:            $Id$
# $HeadURL$


use strict;
use warnings;
use FindBin qw($Bin);
use lib ( -d "$Bin/../lib/perl5" ? "$Bin/../lib/perl5" : "$Bin/../lib" );
use Readonly; Readonly::Scalar our $VERSION => do { my ($r) = q$Revision$ =~ /(\d+)/msx; $r; };

use npg_common::bam_align_irods;

my $align_job = npg_common::bam_align_irods->new_with_options( );

$align_job->run();

1;

__END__


=head1 NAME

bam_aligner_irods - this is to realign some a bam file in irods with a different reference and change and reload it back

=head1 VERSION

$Revision$

=head1 SYNOPSIS

scripts/bam_aligner_irods --id_run 5602 --lane 5 --working_dir /nfs/sf45/bam_realign_rt225652/ --rt_ticket 225652 --reference /lustre/scratch101/sanger/srpipe/references/Homo_sapiens/1000Genomes/all/bwa/human_g1k_v37.fasta --is_paired_read --task bam_realign 

=head1 DESCRIPTION

task list: 

bam_realign

change_bam_header

non_consented_split

strip_bam_tag


=head1 USAGE

=head1 SUBROUTINES/METHODS

=head1 REQUIRED ARGUMENTS

=head1 OPTIONS

=head1 EXIT STATUS

=head1 DIAGNOSTICS

=head1 CONFIGURATION

=head1 CONFIGURATION AND ENVIRONMENT

=head1 INCOMPATIBILITIES

=head1 DEPENDENCIES

=over

=item strict

=item warnings

=item FindBin

=item Readonly

=item npg_common::bam_align_irods

=back

=head1 BUGS AND LIMITATIONS

=head1 AUTHOR

Guoying Qi, E<lt>gq1@sanger.ac.ukE<gt>

=head1 LICENSE AND COPYRIGHT

Copyright (C) 2011 GRL, by Guoying Qi

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=cut
