#!/usr/bin/env perl
#########
# Author:        Marina Gourtovaia
# Maintainer:    $Author$
# Created:       7 March 2011
# Last Modified: $Date$
# Id:            $Id$
# $HeadURL$
#

use strict;
use warnings;
use FindBin qw($Bin);
use lib ( -d "$Bin/../lib/perl5" ? "$Bin/../lib/perl5" : "$Bin/../lib" );
use Carp;
use npg_common::extractor::fastq qw(to_fasta);

use Readonly; Readonly::Scalar our $VERSION => do { my ($r) = q$Revision$ =~ /(\d+)/smx; $r; };

my $num_args = scalar @ARGV;
if (!$num_args) {
    croak 'Input fastq file should be given';
}

my $fastq = $ARGV[0];
my $fasta = undef;
if ($num_args > 1) {
    $fasta = $ARGV[1];
}
to_fasta($fastq, $fasta);

exit 0;

__END__

=head1 NAME

fastq2fasta

=head1 VERSION

$Revision$

=head1 USAGE

 fastq2fasta input_fastq
 fastq2fasta input_fastq output_fasta

=head1 CONFIGURATION

=head1 SYNOPSIS

This script converts a fastq file to a fasta file

=head1 DESCRIPTION

=head1 SUBROUTINES/METHODS

=head1 REQUIRED ARGUMENTS

=head1 OPTIONS

=head1 EXIT STATUS

=head1 DIAGNOSTICS

=head1 CONFIGURATION AND ENVIRONMENT

=head1 DEPENDENCIES

=over

=item strict

=item warnings

=item Carp

=item FindBin

=item npg_common::extractor::fastq

=back

=head1 INCOMPATIBILITIES

=head1 BUGS AND LIMITATIONS

=head1 AUTHOR

Marina Gourtovaia E<lt>mg8@sanger.ac.ukE<gt>

=head1 LICENSE AND COPYRIGHT

Copyright (C) 2011 GRL, by Marina Gourtovaia

This file is part of NPG.

NPG is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

=cut

